#!/bin/bash


#cd /home/haizhi/work/dpdk_2.0
cd /home/haizhi/work/dpdk

export RTE_SDK=`pwd`
export RTE_TARGET=x86_64-native-linuxapp-gcc
make T=${RTE_TARGET} -j12 install CONFIG_RTE_EAL_IGB_UIO=y CONFIG_RTE_LIBRTE_LSXINIC_PMD=y CONFIG_RTE_LSXINIC_RC_KMOD=y CONFIG_RTE_LIBRTE_LSX_PCIEP_BUS=n CONFIG_RTE_KNI_KMOD=y EXTRA_CFLAGS='-fPIC -O0 -g'
make T=${RTE_TARGET} install CONFIG_RTE_EAL_IGB_UIO=y CONFIG_RTE_LIBRTE_LSXINIC_PMD=y CONFIG_RTE_LSXINIC_RC_KMOD=y CONFIG_RTE_LIBRTE_LSX_PCIEP_BUS=n CONFIG_RTE_KNI_KMOD=y EXTRA_CFLAGS='-fPIC -O0 -g' -C examples/port_fwd
make T=${RTE_TARGET} install CONFIG_RTE_EAL_IGB_UIO=y CONFIG_RTE_LIBRTE_LSXINIC_PMD=y CONFIG_RTE_LSXINIC_RC_KMOD=y CONFIG_RTE_LIBRTE_LSX_PCIEP_BUS=n CONFIG_RTE_KNI_KMOD=y EXTRA_CFLAGS='-fPIC -O0 -g' -C examples/kni
make T=${RTE_TARGET} install CONFIG_RTE_EAL_IGB_UIO=y CONFIG_RTE_LIBRTE_LSXINIC_PMD=y CONFIG_RTE_LSXINIC_RC_KMOD=y CONFIG_RTE_LIBRTE_LSX_PCIEP_BUS=n CONFIG_RTE_KNI_KMOD=y EXTRA_CFLAGS='-fPIC -O0 -g' -C examples/l2fwd

